### ISSUE TITLE
dependency is surpported? 依存関係構築できません？

### ISSUE THREAD

**Issue by oppaikir** [unity3d-jp/AssetGraph#11]
I downloaded AssetGrpha (master branch) and try to build out a simple project's AssetBundles,
but Dependencies is always empty.

My project view just like this:
Assets
|-DLs
  ||-Shaders  <- A.shader, B.shader
  ||-Materials <- A.mat, B.mat
  ||-Prefabs <- Cube.prefab, Sphere.prefab

I D&D default 3D Cube / Sphere GameObject to Project view to create prefabs.
Prefab Cube use A material with shader A, 
and Sphere use B material with shader B.

and the nodes design in my AssetGraph is : 
https://i.imgur.com/dAWNwmH.png

but the output material & prefab assetbundles, had no dependency.
https://i.imgur.com/bN7MRrf.png

I try to build assetbundles by using Unity official AssetBundleManager, and its worked.
So, is there anything worng in my AssetGraph setting?

please help me, thanks.

--------------------------------------------------------
はじめまして。
キールと申します。

AssetGraph (master branch) をダウンロードして、簡単なバンドル構造で試しましたが、
ビルドしたAssetBundleに依存関係の構築ができません....

こんな感じのフォルダです：
Assets
|-DLs
  ||-Shaders  <- A.shader, B.shader
  ||-Materials <- A.mat, B.mat
  ||-Prefabs <- Cube.prefab, Sphere.prefab

PrefabはUnityEditor内のDefault CubeとSphereをA、Bマテリアル適用後、
そのままProjectビューにD&Dで生成します。

そしてAssetGraphのノード構造はこういう感じです：
https://i.imgur.com/dAWNwmH.png

ビルド出力した結果、prefabsのAssetBundleに依存関係が一切入ってませんでした。
https://i.imgur.com/bN7MRrf.png
materialsのAssetBundleにも、Shaderへの依存関係がありません。

同じフォルダ構造で、AssetStroeのAssetBundleManagerを利用してビルドすると、
ちゃんと依存関係のあるAssetBundleが出来ています。

AssetGraphの設定、もしくは使い方が間違ってるでしょうか？
宜しくお願い致します。

**Comment by sassembla** [comment]
Thank you for using AssetGraph.

>So, is there anything worng in my AssetGraph setting?
In short, yes,

You mean "dependency" is "these Assets should be in only 1 AssetBundle", right?
of course AssetGraph supports it. 

but AssetGraph is rule-based tool for generating AssetBundles.
means, you should compose the relationship of these assets in AssetGraph.

like this:
<img width="1272" alt="2016-04-15 21 07 01" src="https://cloud.githubusercontent.com/assets/944441/14562463/5062bf58-034f-11e6-8370-70c17ebf6da9.png">


MyPrefabricator.cs samples are below.
`
using UnityEngine;
using UnityEditor;

using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;

public class MyPrefabricator : AssetGraph.PrefabricatorBase {
	
	public override void In (string groupKey, List<AssetGraph.AssetInfo> sources, string recommendedPrefabOutputDir, Func<GameObject, string, bool, string> Prefabricate) {

		/*
			you can see what incoming to this Prefabricator at the Inspector between Prefabricator to next node.
			these codes are based on that information.
		*/

		// get shader data from sources.
		var shaderAssetPath = sources[0].assetPath;// <-maybe the index of source is depends on your environment. 
		var shaderAssetType = sources[0].assetType;
		
		// load shader from AssetDatabase.
		var shader = AssetDatabase.LoadAssetAtPath(shaderAssetPath, shaderAssetType) as Shader;


		// get material data from sources.
		var materialAssetPath = sources[1].assetPath;// <-maybe the index of source is depends on your environment. 
		var materialAssetType = sources[1].assetType;
		
		// load material from AssetDatabase.
		var material = AssetDatabase.LoadAssetAtPath(materialAssetPath, materialAssetType) as Material;
		
		
		// generate cube then set texture to it.
		var cubeObj = GameObject.CreatePrimitive(PrimitiveType.Cube);
		
		var meshRenderer = cubeObj.GetComponent<MeshRenderer>();
		meshRenderer.material = material;
		
		material.shader = shader;
		
		
		// generate prefab from Cube.  
		var generatedPrefabPath = Prefabricate(cubeObj, "cube.prefab", false);
		Debug.Log("prefab:" + generatedPrefabPath + " is generated or already cached.");

		// delete unnecessary cube model from hierarchy.
		GameObject.DestroyImmediate(cubeObj);
	}
}
`

**Comment by sassembla** [comment]
ah-- I found that you means "use same shaders & materials both Cube & Sphere, create these 2 AssetBundles and there are dependency"?

**Comment by oppaikir** [comment]
Hi,  thanks for answers. 

Well,  the "dependency" I mean is one assetbundle dependens to another assetbundle,  which owned the asset that using/linking by other assetbundle's assets. 

For example,  I create a material, and use on a cube and a sphere(two MeshRenderer reference to same material. )

Now I want to build cube.prefab to Cube.assetbundle,  and build sphere.perfab to Sphere.assetbundle. 

If I didn't build the material to an assetbundle, 
then in Cube and Sphere assetbundles will copy material in themselves － I don't want this because data size is coming bigger. (double material,  double texture,  double shader... )

What I want to do is build common data to a assetbundle,  then when I build new assetbundle which have assets link to these common data,  it will not copy,  just dependencies to other assetbundles. 

Can AssetGrpah do this thing?
Thank you very much.

**Comment by oppaikir** [comment]
Oh,  sorry that I typing too slow. 
I saw the answer on the front,  and I think that "output resources" is what I want!!

I  will try it,  thank you!!!

**Comment by sassembla** [comment]
> Can AssetGrpah do this thing?

yes, I' ve updated the comment above. how about that?

**Comment by oppaikir** [comment]
Hi, it's me again.
I tried Bundlizer Node's "output resources" setting, but unfortunately, it doesn't worked.
my test project is here : https://db.tt/OHuj4stJ

I had try two kind of asset graph nodes linking, 
one is just like above pictures yesterday(as my uploaded test project),
another one is more simply : just one material assetbunle, link to another prefabs assetbundle.
But either of them are failed, I cannot see Dependencies in output manifest file.

Am I still missing anything?
thanks for help.

---------------------------------------------------------------------------------

By the way, I found a Bug? in Bundlizer node:
https://i.imgur.com/37ufSe4.png

when I check "output resources" and first connect to another Bundlizer node, 
then connect "bundles" output to BundleBuilder node,
It's ZERO to BundleBuilder node, and all asset & assetbundle output on "resources".

If I link "bundles" output to BundleBuilder node first, then connet from "resources" to another Bundlizer node, it's OK.
assetbundle output to BundleBuilder node by "bundles" output, 
and assets output to another Bundlizer node by "resources" output.

**Comment by sassembla** [comment]
OK, I'll check it,


> found a Bug

YYYEEEESSS its bug, thank you for information!

**Comment by sassembla** [comment]
so, I made below.

<img width="1247" alt="2016-04-16 16 05 26" src="https://cloud.githubusercontent.com/assets/944441/14579992/0a78d742-03fa-11e6-88d1-2eff3df2d727.png">


I've added 2 Prefabricator node before bundlizer.
In these 2 Prefabricator, load Prefab and other sources then attach sources (shader_back, MaterialA) and set it to instantiated Prefab,
then update Prefab itself.

please see "MyPrefabricatorForCube.cs" and "MyPrefabricatorForSphere.cs"
project files are below.
[DependencyTest.zip](https://github.com/unity3d-jp/AssetGraph/files/222114/DependencyTest.zip)



##in advance:

and actually, 

AssetGraph is mainly designed for "create Mass AssetBundles from most raw resources in rule-based flow".
In this design, the Prefab file is mainly generated inside of AssetGraph for binding datas in desired form with generating resources.

very rough ideal data flow is like below.

pattern A: simply bundlize sources.
"a.png" + "b.fbx" + "c.shader" + "d.material" -> import them -> bundlize

usage: Load raw data from AssetBundle for setting up these datas in runtime.


pattern B: construct prefab with imported sources and bundlize sources.
"a.png" + "b.fbx" + "c.shader" + "d.material" -> import them -> + prefab(combined by new prefab with desired shape) -> bundlize

usage: Load data with prefab from AssetBundle for setting up prefab-binded datas in runtime.


In your case, you can use your own prefab,

and also,

You can generate prefab on the Prefabricator node.

like below.

<img width="1252" alt="2016-04-16 17 36 28" src="https://cloud.githubusercontent.com/assets/944441/14579996/169fc198-03fa-11e6-8bbc-6280b6c50998.png">

project files are below.
[DependencyTest2.zip](https://github.com/unity3d-jp/AssetGraph/files/222113/DependencyTest2.zip)

**Comment by oppaikir** [comment]
Hi, thanks for answer and the examples, I'll try it.
thanks again for your help!

**Comment by sassembla** [comment]
you're welcome.

**Comment by hiroki-o** [comment]
Dependency is now created automatically just like standard asset bundle building. You will just create dependencies within assets (such as, by assigning materials to models) and just configure which asset(s) do you want to put into what bundle(s) - then AssetBundle build pipeline automatically figure out inter asset bundle dependencies and configure properly.
