### ISSUE TITLE
Bundlizer resources node contains "AssetBundle"

### ISSUE THREAD

**Issue by sassembla** [unity3d-jp/AssetGraph#12]
"
check "output resources" and first connect to another Bundlizer node, 
then connect "bundles" output to BundleBuilder node,
It's ZERO to BundleBuilder node, and all asset & assetbundle output on "resources".

If link "bundles" output to BundleBuilder node first, then connet from "resources" to another Bundlizer node, it's OK.
assetbundle output to BundleBuilder node by "bundles" output, 
and assets output to another Bundlizer node by "resources" output.
"

![37ufse4](https://cloud.githubusercontent.com/assets/944441/14579230/14151284-03dc-11e6-8453-01fe1ae00627.png)

**Comment by hiroki-o** [comment]
Bundlizer no longer hold resources. closing issue.
