### ISSUE TITLE
Can I bundle DLLs by AssetGraph? 

### ISSUE THREAD

**Issue by alerdenisov** [unity3d-jp/AssetGraph#13]
I tried many ways, but result is no change: `Unrecognized assets cannot be included in AssetBundles`

How I can bundle my dlls with AssetGraph?

**Comment by sassembla** [comment]
Maybe this article helps you.

http://answers.unity3d.com/questions/259569/how-to-compile-script-to-include-it-to-assetbundle.html

**Comment by alerdenisov** [comment]
It's not so convinient for me, but thanks. I will try to extend AssetGraph with extra nodes for copy and rename files

**Comment by sassembla** [comment]
Yeah. 
You can run your codes on Prefabricator. you can do it in Prefabricator node. (That's not intended but enable.)
