### ISSUE TITLE
How can I filter Prefab in a filter node?

### ISSUE THREAD

**Issue by yangruihan** [unity3d-jp/AssetGraph#16]
I notice that I can't filter a prefab in a filter node, so what can I do to compress a prefab into a AssetBundle. Use Prefabricator node?

**Comment by sassembla** [comment]
You should use Prefabricator only if you want to generate prefab programatically. 
and so you can filter your own .prefab files in Filter Node. 

how about this?
<img width="1046" alt="2016-09-26 22 03 35" src="https://cloud.githubusercontent.com/assets/944441/18835484/3eee7ede-8436-11e6-9261-efd0cddf0a5a.png">


If you can not find your prefab resources on the connection-line between nodes, please check Loader Node's path and your prefab file path.

And below is some example of making AssetBundle from prefab.

<img width="702" alt="2016-09-26 22 12 50" src="https://cloud.githubusercontent.com/assets/944441/18835513/64b9b8f4-8436-11e6-9599-253af5716298.png">

**Comment by yangruihan** [comment]
I got it!
Thanks very much :+1:  :)
