### ISSUE TITLE
Looks Amazing for bundle build, but what is the right way to load them ?

### ISSUE THREAD

**Issue by FXCarl** [unity3d-jp/AssetGraph#4]
The readme file did not talk about the bundle dependencies.

**Comment by sassembla** [comment]
bundle with dependencies is not supported yet. still work in progress.

**Comment by sassembla** [comment]
I'm adding "use bundlized assets to other bundle" like this image.
<img width="940" alt="2016-03-15 1 33 12" src="https://cloud.githubusercontent.com/assets/944441/13751860/7a9f5010-ea4f-11e5-959a-fad8c967b37c.png">

**Comment by sassembla** [comment]
bundle with dependency is now supported on master branch. (but undocumented yet.)

you can use bundlized resources as part of other assetbundles.
Bundlizer's inspector -> check "Output Resources" shows new connection point.
